# Table information

metadata: Marusagar Express | Running timetables | Southern India
full table:
No_ | Station_Code | Station                  | Arrival | Departure | Kilometers | Day_
---------------------------------------------------------------------------------------
1   | ERS          | Ernakulam Jn             | Source  | 19:50     | 0          | 1   
2   | AWY          | Alwaye                   | 20:20   | 20:25     | 20         | 1   
3   | TCR          | Thrissur Railway Station | 21:20   | 21:25     | 75         | 1   
4   | SRR          | Shoranur Jn              | 22:15   | 22:25     | 107        | 1   
5   | CLT          | Kozhikode                | 00:25   | 00:30     | 193        | 2   
6   | CAN          | Cannanore (Kannur)       | 02:15   | 02:20     | 283        | 2   
7   | KGQ          | Kasaragod                | 03:58   | 04:00     | 368        | 2   
8   | KNKD         | Mangalore Jn             | 04:55   | 05:05     | 419        | 2   
9   | UD           | Udupi                    | 06:21   | 06:22     | 501        | 2   
10  | KUDA         | Kundapura                | 06:49   | 06:50     | 545        | 2   
11  | BTKL         | Bhatkal                  | 07:34   | 07:35     | 614        | 2   
12  | GOK          | Gokarna Road             | 08:43   | 08:44     | 718        | 2   
13  | KAWR         | Karwar                   | 09:28   | 09:30     | 768        | 2   
14  | MAO          | Madgaon Jn               | 10:45   | 10:55     | 850        | 2   
15  | THVM         | Thivim                   | 11:45   | 11:46     | 914        | 2   
16  | RN           | Ratnagiri                | 14:15   | 14:20     | 1184       | 2   
17  | VEER         | Veer                     | 17:24   | 17:25     | 1404       | 2   
18  | PNVL         | Panvel                   | 19:50   | 19:55     | 1547       | 2   
19  | BSR          | Vasai Road               | 21:05   | 21:10     | 1614       | 2   
20  | VAPI         | Vapi                     | 22:51   | 22:52     | 1736       | 2   
21  | ST           | Surat                    | 00:20   | 00:25     | 1829       | 3   
22  | BRC          | Vadodara Jn              | 02:08   | 02:18     | 1958       | 3   
23  | RTM          | Ratlam Jn                | 06:25   | 06:45     | 2219       | 3   
24  | NAD          | Nagda Jn                 | 07:27   | 07:29     | 2261       | 3   
25  | KOTA         | Kota Jn                  | 10:00   | 10:10     | 2486       | 3   
26  | SWM          | Sawai Madhopur           | 11:45   | 12:05     | 2593       | 3   
27  | JP           | Jaipur                   | 14:05   | 14:20     | 2725       | 3   
28  | KSG          | Kishangarh               | 16:21   | 16:23     | 2830       | 3   

# Statement
The train timetable in South India for the Marusagar Express with station code Awy shows an arrival time of 20:20.

# Response
```python
import pandas as pd

def expand_statement_pattern(df):
    statement_pattern = "The train timetable in {region} for the {train_name} with station code {station_code} shows an arrival time of {arrival_time}."
    expanded_statement_list = []

    for index, row in df.iterrows():
        region = row['Day_']
        train_name = df['Caption'].split('|')[0].strip()
        station_code = row['Station_Code']
        arrival_time = row['Arrival']

        expanded_statement = statement_pattern.format(region=region, train_name=train_name, station_code=station_code, arrival_time=arrival_time)
        expanded_statement_list.append(expanded_statement)

    return statement_pattern, expanded_statement_list
```

# Exception
Traceback (most recent call last):
  File "/home/go203302/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Caption'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/go203302/mtr-lftqa-dataset/expand_statement.py", line 136, in <module>
    statement_pattern, expanded_statement_list = expand_statement_pattern(
  File "<string>", line 9, in expand_statement_pattern
  File "/home/go203302/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/go203302/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Caption'

